#!/bin/sh

# Debian post install package. Add user, set perms, copy default configs over
# if no config in place, start server

# if the server init script exists, call it to stop
if [ -f /etc/init.d/streamingserver ]; then
    /etc/init.d/streamingserver stop
fi

# Add system user
echo 'Adding qtss user & group'
/usr/sbin/useradd qtss > /dev/null 2>&1

# if there is no qtuser file, move the dist version over, and update the admin user
# to the default

if [ ! -f /etc/streaming/qtusers ]; then
        echo 'Configuring default admin/admin account for dss'
        cp /etc/streaming/qtusers.dist /etc/streaming/qtusers
        cp /etc/streaming/qtgroups.dist /etc/streaming/qtgroups

        # Add the new admin username to /etc/streaming/qtusers
	/usr/local/bin/qtpasswd -p admin admin
	
	# Add the new admin username to /etc/streaming/qtgroups
	# and delete the default admin username
	echo admin: admin > /etc/streaming/qtgroups.tmp
	mv /etc/streaming/qtgroups.tmp /etc/streaming/qtgroups
	
	# Remove the default admin username to /etc/streaming/qtusers
	/usr/local/bin/qtpasswd -F -d 'aGFja21l' > /dev/null
fi


echo 'Setting the ownsership to qtss on /etc/streaming'
chown -R -f qtss /etc/streaming/

echo 'Creating /var/streaming/playlists'
mkdir -p /var/streaming/playlists

echo 'setting mode to 770 on /var/streaming/playlists'
chmod 770 /var/streaming/playlists
echo 'setting mode to 775 on /usr/local/movies'
chmod 775 /usr/local/movies

echo 'Setting the ownsership to qtss on /var/streaming'
chown -R -f qtss /var/streaming/
echo 'Setting the ownsership to qtss on /usr/local/movies'
chown -R -f qtss /usr/local/movies/

echo 'Setting the service to auto-start'
/usr/sbin/update-rc.d streamingserver defaults

if [ ! -f /etc/streaming/streamingserver.xml ]
    echo 'Creating default config file'
    /usr/local/sbin/DarwinStreamingServer -x
    cp /etc/streaming/streamingserver.xml /etc/streaming/streamingserver.xml.dist
    echo 'Setting the ownsership to qtss:root on /etc/streaming/streamingserver.xml'
chown -f qtss /etc/streaming/streamingserver.xml
fi


echo 'Starting the service'
/etc/init.d/streamingserver start

