#!/bin/sh  

# Debian pre install removal package. stop server, remove binaries. leave configs

# Stop server


if [ -f /etc/init.d/streamingserver ]; then
        echo Stopping Server
        /etc/init.d/streamingserver stop
fi

# Remove old stuff

echo Removing previous versions of Darwin Streaming Server
if [ -f /usr/local/sbin/DarwinStreamingServer ]; then
        echo removing /usr/local/sbin/DarwinStreamingServer
        rm -f /usr/local/sbin/DarwinStreamingServer 
fi

if [ -f /usr/local/bin/PlaylistBroadcaster ]; then
        echo removing /usr/local/bin/PlaylistBroadcaster
        rm -f /usr/local/bin/PlaylistBroadcaster
fi

if [ -f /usr/local/bin/MP3Broadcaster ]; then
        echo removing /usr/local/bin/MP3Broadcaster
        rm -f /usr/local/bin/MP3Broadcaster
fi

if [ -f /usr/local/bin/qtpasswd ]; then
        echo removing /usr/local/bin/qtpasswd
        rm -f /usr/local/bin/qtpasswd
fi

if [ -f /usr/local/sbin/streamingadminserver.pl ]; then
        echo removing /usr/local/sbin/streamingadminserver.pl
        rm -f /usr/local/sbin/streamingadminserver.pl
fi

if [ -f /usr/local/bin/streamingadminserver.pl ]; then
        echo removing /usr/local/bin/streamingadminserver.pl
        rm -f /usr/local/bin/streamingadminserver.pl
fi

if [ -f /usr/local/bin/SpamPro ]; then
        echo removing /usr/local/bin/SpamPro
        rm -f /usr/local/bin/SpamPro
fi

if [ -e StreamingLoadTool ]; then
    if [ -f /usr/local/bin/StreamingLoadTool ]; then
            echo removing /usr/local/bin/StreamingLoadTool
            rm -f /usr/local/bin/StreamingLoadTool
    fi
fi


# Remove rc links
update-rc.d -f streamingserver remove


